---
title: 『 破晓. 』
author: ' M.W. from Apocalypse'
date: '2010-10-07'
slug: XYMHC
categories:
  - Story
  - XY Mental Health Centre
tags:
  - XY Mental Health Centre
---

我曾经梦想过这么一幅画面。

画面中一个安定淡漠的男子站在悬崖的尽头，绛红为大地蔚蓝为穹苍。他的脚下是一望无际的丛林，身后是一座阴沉沉的岛屿。岛屿上有座塔，也许还有一座监狱，谁知道呢。

而他就站在那里，他什么也不做。风衣飘扬着，他不动声色。透过额间诡异的发丝他能看到这世界，他能看到这一切。

他就像是一个监视者。

<!--more-->

我曾经梦想过这么一幅画面。

画面中一个安定淡漠的男子站在悬崖的尽头，绛红为大地蔚蓝为穹苍。他的脚下是一望无际的丛林，身后是一座阴沉沉的岛屿。岛屿上有座塔，也许还有一座监狱，谁知道呢。

而他就站在那里，他什么也不做。风衣飘扬着，他不动声色。透过额间诡异的发丝他能看到这世界，他能看到这一切。

他就像是一个监视者。
 
&nbsp;

而他的眼神锐利如刀。他向着一望无际的丛林伸出手，像是在邀请什么，但实际上他没有动。他还是没有动，一切幻觉，也是真实。他紧锁的眉头给人踏实而严谨的感觉，但是在这一刻他像是一个流浪者，又像是一个征服者。他瞳孔的斑斓给人混沌的错觉，可是他的表情还是如此淡漠安定。

这个画面是什么，我不明白。我也不会去明白。我曾经梦想过很多画面。最早是暮落晨光塔，然后经历了数次变更，从北极星围绕的倒计时和深夜寒街的夜行人，这些画面从未带给我什么，也从未预言过什么。我不是Leader中的卫海洋，他是预言者；更不是佳境中的金科延，他是监视者。

想到这里我也不清楚我是要表达什么了。反正这是深夜，这是10-10-07的凌晨，时针和分针划下觥筹交错的记衡点，指向2与12的30°。三年前我刚从这里启程，周围浮光四溢带有凌晨的清气，东边虹彩左手幽兰，步往灿烂的旅途。我从未想过我会在各种文字赛事上取得大奖，尽管我是那么渴望它。投给新概念的稿件，从最初想要表达影子之城和浴室的交错的《复仇I》，到继续修改却不尽如人意的《复仇II》；从初三双重人格自我影响的《惫春I》，到未发出来的暗夜远居地记录笔记《惫春IV》；从初中三年厦门的温柔《南北》，到黑暗和高中潮汐并行涌来的《安魂夜曲》。我能深刻感觉到，又不能感觉到关于文字的东西。

那是虚浮的。
 
&nbsp;

音乐略过。似乎我很喜欢提这两样呢。

而我现在坐在电脑前，时间已经指向2:07，夜色弥漫，日光灯灿烂。父母已睡下，朋友已离散。相机在左手，手机在右手。PSP扔给SGO，因为他需要。『夏夜幻灭事件』中的老友记已结束，连迷失也已结束，我还能剩下多少东西？DHA的牛奶已喝光，素净一般的夜已消失，连那个人也已不再出现，忙于高三。前几天在手机上听到了熟悉的动漫音乐，来自PSP复制予的，里面有家教，过往的热血澎湃。有钢炼，05年的黑色汹涌潮汐。有钢炼II，伟大的传说。有寒蝉，08年黑化的预兆。有School Days，09年黑化的狰狞。

这过往的一切，在对我诉说。
 
&nbsp;

本是想将这篇写成一篇温柔沉溺的小杂文，投给新概念，但是写着写着变了味，也就失败了。不到一个月的时间，只能改写《深渊》和《北夜》了。对文字的兴趣盎然也逐渐变成了漠视淡然，平稳淡定的诗句也再也无法出现。文学社的职位已辞，新概念以后，也无法再将感情释放。

尽管，他们哽咽了太久。

我一直很想对自己说声再见，然后终结它。但却有声音一直在制止我，他们提醒我继续写下去，纵然我不知道我能写什么，又是需要写什么。于是凑字数型地继续提到了时间，现在是10-10-07的02-21，深夜逐渐逼近，灯光依旧不动声色，我有点饿了。过往是温柔的情感，高中三年的生活却告诉了我什么叫梦想就是梦想，绝不可能比现实更重要。意识流掩盖了我，光远逐步占据上风，遇到事情，也不是以温柔的神色，而是以冷静的思考代入。面对女生时不像网络上那么开放，有点犹豫，有点退避三舍唯恐避之不及。现实让我越来越渴望未来，也越来越思念过去。

这样，才能知道平和的重要性。

小羽说，我没有脾气。

不知为何想到这句话。作为深夜低语的终结。

附新歌曲录《My Way我的路》列表及其歌词一首。已作曲。将在世纪末剩余2篇歌曲结束后一阵子，直接全部发上。以十二月形式记录，此为五月。
 
&nbsp;

一月.旅途 七月.诗篇

二月.夜雨 八月.荒城

三月.塔拉九月.未央

四月.海下歌II 十月.破晓

五月.永恒 十一月.岛屿

六月.葵海 十二月.千阳

五月.永恒
 
&nbsp;

平静的未来 不安的伤害（妩媚的伤痕 平缓的懈怠）

夜色里你能听见我的离开吗（白昼里你能听见我的归来吗）

温柔的城市 呢喃的晨雾（未醒的城市 流淌的晨雾）

恍惚间差点以为这就是永恒（恍惚间差点以为这就是永恒）

岛屿的破晓 荒城的千阳（塔拉的葵海 诗篇的深海）

夜雨倾盆而下从不知疲倦（秘密在身下悄然地流转）

在这未央里 我独自启程（东边的虹彩 左手的幽兰）

去寻找那如旅途一般灿烂的黄昏（这水蓝的旅途灿烂归于平凡）

多期待 永恒的未来

五月海 思念不到来（蔚蓝海 夜色中盛开）

火车驶向平稳的高山

越安静 过去越腐败

旧信来 掉漆邮筒在

时间停在永恒的小站（永恒停在五月的小站）
 
&nbsp;

晚安 镜潋。

Good Night Mirror Wave.
 
&nbsp;

末世镜潋  
2010年10月7日，林世界

