---
title: 十二月礼之歌II
author: 'M.W. from Apocalypse'
date: '2011-11-07'
slug: Poem
categories:
  - Poem
tags:
  - Poem
---

文 / M.W. from Apocalypse

[2011.11.07六月][删]  
[2012.02.09八月]  
[2012.04.09三月][删]  
[2013.05.21一月]  
[2013.11.12十二月]  
[2017.11.30三月]  

&nbsp;

**[一月 致你]**

可是我从来未听过你的名字  
是解冻的海鸥，抑或是远方的来信？  
万物尚未解放，严冬阻碍光阴，  
一月，我在来客与监视者的目光中  
独自前行。  

&nbsp;

**[三月 致张枣]**

我不清楚你是什么模样，总之  
我插上一根蜡烛，让它的  
灯火照亮  
空旷的麦田，植满铁锈的深夜  
再溜向屋外。  

究竟那是什么？我叹气，看向  
群山，  
走向婚嫁的影子，任凭冬风  
吞食声音，大雪覆盖平原。可  
你曾经也是如此。  
低声，进了门，  
面向长远的钟爱和诗，  
不想进食，欲望低下，  
转向一支火烛。  

可为什么会这样？  
你望向窗外，湖水结了冰，你  
为何不睡去，在冬天，  
没有鸟儿的时节，千雪封山  
在此熄灭蜡烛，持续地沉睡。  
我也挽起头发，推开门，  
纵使这世界需要你，我也  
冷冰冰地走动，陷入漫长的夜晚。  

我不清楚这空旷的平原，  
这十月之水，究竟有什么意义。你  
离开时，究竟那是什么声音，所环绕的  
乌鸦们呼啦啦地飞过，影子沉迷于冬风  
此时我又听见自己的声音  
看不见你的背影，长夜如铁。  

离开时，你又匆匆  
你举起火烛时，已照不亮  
群山，  
你挽起冻死的马缰，不再回头  

&nbsp;

**[八月 致宽恕]**

上主造物用了七日。  
点滴碎石，苦行而叹  
可他必将用那含泪的眼眸  
从水和尘埃出发，  
找原始的野兽，浅谷的鱼  
去吞暴虐，杀戮和敬慕  

意乱情迷的第二日，世界开始复甦。  
可她永远不知道，罪恶悄悄燃烧？  
越洋而来的判决深藏海岛，  
深海正在高歌，意象终结了未来  

可是在未来。又会是谁，  
于我深山觐见之时冻结。  
它解开大地肮脏的神经  
挂起我，像挂起一轮皓月：  
谴责，鞭笞；怀疑，愉悦；  
笔尖已经嘶哑，杯盏已经安眠。  
&emsp;&emsp;&emsp;&emsp;上主。请宽恕她的卑微梦想：  
就像宽恕我深藏利刃，抵喉相见。  

&nbsp;

**[十二月 致终结]**

男人走了，他便不可回头  
在十二月的温暖的冬天  
将要启行，路过故事  
“看呐，他在走着！”  
身旁的孩子们笑道，聚拢在他的身旁，好奇的眼神  
注视着，欢笑着，用石头砸在他的身上  

他到了第二个城镇，丢失了名字  
也就不能说话，他听着，看着。  
长长的谴责书被雕刻在石碑上，  
历史遗忘不同的事物，  
人们前行，化作飞蚁。  

到达第三座城堡的时候，森林正在开放  
蘑菇种植于污秽的流言，长蛇早已蜕皮  
他交易听觉，得到了解真与恶的权利  
“我的尸骨将长埋于此”  
幕布拉下，长诗宣告终场。  

“我不可告知世人；我不可被万物阻拦。”  
男人依旧能看见，能触摸，能感觉。  
他看见的，一只鹿飞快地奔过平原；  
飞鸟掠过天空，触摸到的；  
潮湿的空气，混杂泥土中绝望的香味。  

那是永恒之花，抑是间隙而行的灵感  
选择了不同的，终是不同的道路  

不可嘲笑，世界因此而美丽。  
