---
title: "VII：The road to Upper Peninsula. (17/23)"
author: "C from NAND city"
date: "2019-04-06"
slug: imago7
categories:
- Story
- imago
tags: Story
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

To Lapis Lazuli.

<!--more-->

*For H. P. Passeriformes & P. Ar. Rosaceae*

文 / C from NAND city

&nbsp;

**1（故事.混杂纪）2018.11.20**

这可能是故事最早的基调——格式没有意义。日记这种东西，最佳的方式就是让写作者感到舒适，因此它不需要被别人看懂，也不需要遵循着一定的规则移动。如果按照规则、密码学的方式来有格调地写作，那便变成了故事。男子这么想着。

因此他已经决定了新的日记必须遵循本我的快乐原则。只是单纯地、忠实地、只在灵感迸发的一刹那——将所有转瞬即逝的东西一一记录下来。

他又想到焚毁的羽园。在自我透露的会议中他曾经被询问过：“什么是你痛苦/快乐的时刻？”他毫不犹豫地就画出了在他脑海中的那个场景：天空中下着羽状的鹅毛大雪——那是他一辈子渴求而不可得的东西。在那个片段的回忆中，羽园焚毁，大树变成了通往荣格城堡深渊的残毁通路。尽管在后续的过程中，他试过很多的方式——隐瞒、欺骗自我、接纳、仇恨或是回归的爱意，那些东西都变成了他最后的青春，消散于无尽的飞花中——尽管羽园被镜潋尝试修修补补，试图复原成原来的样子，那造成的伤害却一辈子无法修复，成了男子恪守的信条，指导并告知他。

他又想到在深渊中心的咖啡馆中，两人保持着距离，试图以成年人的姿态交谈。一方带着微弱的仇恨；一方带着复杂的情感。那最后内化成了深渊中的某个幻象，成了自我解析、M幻影的出现地。在红茶的香气中，男子听到了清晰的那句话。

那变成了他新的伤痕。那就是信条本身。这么多年的心理学学习中，他已经明白了一点——即便自知力能够高度上涨到理性分析自我，一些东西终究是逃避不了的，必须由他人带来的。那很重要。就像是男子很明白自己的病症，也恪守拒绝亲密关系这一点，但当她对他说出：“不要去祸害他人”这句话的时候，他还是受到了5%的伤害。

这5%的伤害最后转化成歉意的逆转，成了5%的仇恨，又在深渊的呈现中，转化为95%的爱意。但信条始终不变。男子至今还是害怕亲密关系的建立，并以那句话作为恪守的信条。尽管不能将所有的责任推诿予这句话——其实更多的应该是自己的人格所导致的——但他还是坚信不疑。

就像是在12年10月之后，他再也没有体会到“快乐”这一感觉了。而这是他最近才意识到的。
 
&nbsp;

**2（羽园.重建） 2019.03.28/04.06**

第二次人格战争以人形之间脆弱关系的相互构建结束。如同链式反应一般，你拉着我，我拉着你。爱欲、温柔、常态和冷漠成熟互相交织，在其之上，是浮动的，透明而安静的心理学观测人形，是纯粹的自由主义。

镜潋第一次意识到他被拯救是在2010年，借由林世界复生后，在血红色的天空下以温和歌声的回应他的，是虚拟的歌者。尽管我们不能将所有事物分为正确的，抑或是错误的；但是两位旅人很清楚什么是积极的情感，而什么又是消极的。那一刻起他获得的东西，不止是新生的希望，更是一种突然而生的勇气，帮助他成功逃离了亦非城。而如今，他也常梦见当时的他，在寒冷的街道中，通行经过亦非城不同区域。

第二次不能称作被拯救。尽管在心脏的世界里，有新的区域林立而起了——那是羽园的建立。新的意象带来的，是新生的特殊的情感。如果说镜湖代表了人形的温柔；林世界代表对未来的希望，那么羽园就是理想的某个东西的存放地。镜潋自己可能也没有意识到，一开始降临于羽园的，是无尽的飞花状大雪；时间可能要倒溯回2004年那个沉静的夏天，再移植至2006年，2008年和2011年。

在编织者的最后一个镜头里，镜潋将火把扔向前方正在熊熊燃烧的羽园。骑士卸下了盔甲后，他选择了自己毁掉自己应保卫的树木，再顺着情感的残骸一路向下，抵达心理学的深渊领域。那里是吞噬了前七个意象的，究极的未知所在。

第三次被拯救，是已经在深渊之后了。荣格城堡本就是真理与情感的扭曲融合之物，他也自然可以自由穿梭于羽园和荣格城堡之间——他们同属于同一片大陆。镜潋先细心地修复了羽园，再抵达深渊——那可能是自佳境岛后，他面临的第二场残酷的战争，即便是离开西方荣格城堡，都没有带给他如此厚重的压力。在深渊的真相被揭露后，男子接纳了自己，与5%的仇恨和解，再接受95%的爱意。

随后是深渊消亡。男子真正意识到自己不再寄居而生95%的爱意，而是将其尽可能地永久封存，并作为羽园重建的燃料。他试图在原有的残骸上，使用第二次人格战争所剩余的一些东西，再塑造一个天青色的雕像。

我们称之为爱欲或温柔的融合体也大抵是如此了。在阴暗幽深的深渊中，他曾经一度看见了太阳。如同影子一般自我厌恶的他，如同飞蛾扑火般地望向炙热的阳光——曾经在2011年，他也这么做；最后在次年，将自己和树木葬身于熊熊的大火中，最后烧得满身是血，沉没于白雪的平原。这一次他很精妙地，小心而谨慎地与太阳保持距离，只是享受而蚕食她所带来的温柔，却绝不靠近。在残忍而平然的现实中，这可能是活下去最好的办法。

为了感激她，他阅读《圣经》，并塑起天青石做的雕像。在“情感”被找回后，人形们忙碌着，最后将羽园从“伤痕”修复成“对未来的希望和勇气”，并塑造雕像，以纪念或是保存那些曾经的阳光：她们散发着柔和的热量，以印象和理想为形，重新带给旅人们探索未知恐惧的勇敢，和与其共生的积极情感。“这似乎就像是卑微的影子一般。”光远有时还会自嘲，“向着太阳而生。”

但那又有什么不好呢？
 
&nbsp;

**3（东方荣格城堡，告别仪式长章，上）**

\>>1 2019.06.06

在最后的一年里，旅人团体们在羽园和东方荣格城堡之间开始进行往返，整理收拾两个地域的杂物，并尝试着将其规划成具有清晰逻辑条理的意象。和过去抛弃的六个童年意象不同，羽园的通道将逐步向西方荣格城堡打开，男子决心将返回那儿。

天青石雕群依然矗立在羽园侧旁。男子没有想过重新将石雕粉碎打散成风景，而是保留在这座公园里，成为潜在心理现象的一种。在这样的生活里，他感受到孤独，也体会到快乐。未来的路会是什么样子，镜潋和光远也不太明白，他们只知道自己接下来的道路，比想象中的要漫长得许多。

\>>2 2019.06.17

旅人团体们真正意识到告别这件事是在离开了深渊后四个月了。纵使他明白自己即将离开东方的荣格城堡，重新返回西方——这可能意味着告别，他似懂非懂。镜潋此刻又想起了自己早期在旧大陆的童年时光，他从来没有真正与谁告过别。真正下决心离开的时候，旧大陆的旅程已经终结，而那是他，或者他们不想去回忆的过去，他甚至欺骗了自己，下定决心让自己也忘记掉那段时光。

可这次不同。进入新大陆以来，他往往告别。无论是离开羽园，抑或是在东方城堡内慌乱的三年时光，还是西方荣格城堡，抑或是新生成的虚假亦非城——即回到东方城堡的深渊。每一段经历，他在和路上遇到的风景告别。很平静的是，他确实是很安逸地接受了每一次离别，纵使这可能使他变得更加孤僻，独立，顽强固执，他往往做告别。可能是生理机能的逐步退化，他的脑海里已经逐渐回忆不起过去三年间发生在东方荣格城堡的第一次人格战争，究竟遇到过怎样的人，遭遇过怎样的背叛，或者是遇到过怎样的风景。唯一可以确定的是，C与他们做了坚决的告别；绝非往日如佳境岛或仙岳一般，带有恐慌的逃离、而是下定决心，温和安定的，做了“你再也与我无关”的告别。

这往往比带有情绪的离别更加绝望。

旅人们这几个月过得不是很好。他们尝试着整理东方城堡中的残破废墟。二楼佳境岛侵入的房间已经被完全整理干净，成为了一间普通的杂物室，他人再也看不出来光远曾经第一次死在那儿。镜潋被囚禁的大床房也是，刑具和锁被彻底清除掉，大家和睦地住在房间里，偶尔还能透过天窗，看向羽园的天青石雕。在这样的探索中，他们发觉孤单是一种原罪。固执而漫长的告别仪式需要人类拥有极为顽强的精神去执行。

然后就在近日，对深渊房的整理终于结束。旧有的虚假意象被彻底清除，房间恢复了它原本的样子。于是第一次告别，终于开始。

\>>3 2019.06.17

亦非城第五区充斥着虚假的意象。从咖啡厅到橙黄色的晚灯，无一不是从重复的梦境中直接摘抄而来。但是情感是真实的。在那段时间里，晨夕对于羽园的意象触发者的拜访使他痛苦纠缠，最后花了长达半年的时间，与自己和解，对她进行了告别的仪式。你看，故事是一环接一环的。她触发了深渊，而另一位歌者扮演了太阳的角色，如同早年的Miku一样，带领他离开深渊，于是情感重新连接。近日以来旅人们思考着如何从精神层面清除掉深渊的情感连接，最后选择了暂时移除掉太阳，将她作为可以长期保存，却无法触及内核的天青石雕，放置在羽园深处。其他的情感链接，大部分早已在深渊时期就已经逐步消散，再借由这数个月的时间，逐步瓦解。当晨夕结束了现实中的一些事之后，加入了一个新的团体，他才逐步地解除自己的移情。

这就是第一次告别的开始与终结。晨夕不再回望过去。不再去回望深渊中那些杀伐的噪声，拖着他的战友抑或是反目成仇的敌人，终究会在某个春天的湿润的晚上，随着一通电话彻底消散。他开始为自己感到雀跃——即使孤独，但我至少留存了那块天青石雕。——而我将移居到另一个新的，破旧却充满的梦想的地方，开始自己崭新的生活。

他为此感到快乐。这应是在近七年以后，他第一次感到快乐。

\>>4 2019.09.09

深陷于荣格城堡内的第三个月，镜潋终于意识到了短期细碎的记录是没有多大意义的，也没有很强烈的艺术色彩。“过于凌乱而无法整合成宏大的光。”他这么告诫自己，又翻开了一本书。

所以故事可能即将停留在极为短暂的夜晚里。当他们透过三层天井瞭望羽园的天青石雕时，羽园正在荒芜的大地中枯萎。两座天青石雕饱受风吹雨打。尽管在这座类似于仙岳（唯一不同的是允许你写下一些仍能保存于记忆中的短小日记）的坚硬城堡中时间和孤单感被无限拉长，但是他仍然很满意自己的生活。

相反地，羽园正在逐步崩坏。

光远承担了观察者的职位。在心理学人形暂时离开后，他终于有机会拿起他曾经遗忘的吉他，一边享受自我，一边观测羽园。天青石雕纵使可以反射出一定量的月光，来让他们在这黑暗里有着一丝光亮；可是这光亮也足够微弱仅仅能让他们进行阅读，以不至于迷失自我。情绪是无法消解的，过度的东西则不是靠理性能够解散——这点旅人们在数年前就已经明白。天青石雕所代表的，可能并且一定仅仅是一个模具，一个他们理想状态下的太阳。

它所承载的现实，没有丝毫意义。那可能是极度疯狂的消息。即使有再强大的，足够理性的存在都无法合理化的消息。这也有可能是因为告别做得不够彻底，人终归是社会性的生物。

男子这么想着，又喝了一杯酒，安稳地睡了。在梦中，他可能看见了另一个故事。那是和这段故事截然不同，甚至毫无关系的，一段较为美妙的童话。

\>>5 2019.10.07于12.29

在反复拉扯的爱欲中，镜潋体验了一段新的人生。当几位友人都在反复告诫他抛弃现实，回归这段只有纯粹自我的旅行时，他仍然固执着望向那座天青石雕，并试图从坚硬的雕像内部寻找些什么。荣格城堡的意象已经完全解析明了并没有任何留念，光远和晨夕做着对应旅行的准备，以前往西方。只有镜潋仍然固执着坐在床上，顺从自己的内心，寻找那一丝可能性。

在龟缩自闭与反复开放的过程中，他又想起了网络上传播的迷因，不由得开始自嘲。在这数个月的时间里，传统固执的他又夺回了观测者的位置，并不死心地日日夜夜照看天青石雕。在那段时间里，他又开始做梦。与往日的日日悲梦不同的是，这次的梦境总会带有歹毒的恶意抑或是平静善良的信念，共同交错着织出一些他自己都无法解读的故事；而就在这故事的朗诵间，整座城堡正在发生悄然的变化。

这是他第一次体验到意象的变化。往日的意象坚固如金石，往往只可能是一个宏大的传奇，而他在儿童的发展中逐渐体验到自己，并将其记录成谨慎的旅行叙事。——他只可能从上一个意象奔赴下一个意象，并继续自己的旅途。而这次，他是第一次感受到了第八意象的强大之处。
 
&nbsp;

羽园旋转着溶解了。它本就建立在宏大的荣格城堡之上。而当土地不断流失，操作性概念也被迅疾破坏，它又有什么理由存在于这个世界里呢？或者是说，早在数年前它就应该消失了。而随着羽园的向下坠落，荣格城堡东区逐渐塌陷，人群四散着奔逃。

再也没有什么一楼，二楼，三楼了。往日的审讯室，意象寄生的地方，交易大厅等已经全数消失。重新建构并生成的，是一个明亮清澈的营地。闻讯从其他地方赶回来的旅人们只看见月光从天空中洒落，照耀在荣格城堡曾经的废墟上。在这篇废墟里，人群们熙熙攘攘地回归，重新建起了小众但繁荣的市场，街道和王政大厅。在政治的大堂里，人群模拟荣格城堡原先的建筑结构，建立了三层房屋。三层是休息室；二层是代表权势和成熟的人群的聚会场，人们在这里觥筹交错，低声交谈，并重新组织起欢乐和交易的宴会。一层是燃烧着咆哮的火焰的圣诞大厅。在暖炉旁放着数张沙发以供旅人休息（但镜潋不会想到，顽皮的外部人形会借用这个场景，重新勾起他短期的双向爱欲）。

但重新建立起的城堡终究只是小型。随着城堡的构造被重新组织，大厅变成了开放式，显得更为清澈透明。在小型的房屋外，是大片的，原先没有的野营地。而在这座不知名的营地里，人们建立起属于自己的小型团体，建立市场和小型工厂，抑或是单人作坊，互相交织。在飓风即将来临的季节里，也不知道这座下陷的营地是否安全。

镜潋等人也无法判断这样的变迁是好是坏。这毕竟只是一次短暂的变化，在他的预定计划里，即便这样的变化会给他带来短时间的难过情绪，他也即将坚信着要离开这里，前往下一个半意象。想到这里，他将诗集扔进了大厅的火焰中，又回头看向大厅内的天青石雕。

他的感情仍然在。而沙发上坐着的那个顽皮却安静的精灵也同样能够安抚他躁动的黑暗情绪。只是这一刻他确实明白，和在佳境岛的他不一样——那时的他，两个情感都是真实的；这次的他，两个爱欲都是虚假的。
这可能是来源于他满怀的恶意。想到这里，他的右腿开始剧烈地疼痛。
 
&nbsp;

**4（故事.夜曲纪） 2019.10.03于2019.12.29**

在迅疾而过的夜晚中，男子梦见了很多东西。这可能是近些年他难能可贵的体验了——体验那些舒适、温暖的，他却无法解读的故事和梦境，这也可能是近些年他的第一次。就像是又回到了那个风雨交加的，寒冷的夜晚中，他向着悬崖外伸出手邀请，又犹豫着缩回、返回城市的街道。这些他人无法解读的故事往往充满着魅力，将一个成熟的成年人重新打回到温暖的炉火旁，缩在被窝里望向枕边模糊的身影，希冀着能够再听到一个床边故事。想到这里，他沉沉睡去。

在这样宏大的，充满着隐喻的叙事里，任何人为理性的或是定量的解读都显得没有意义了。男子在梦境中嗅到了消毒水的香味，而这可能是传导了数次的深刻概念所导致的。他起身后，就可以立即去拜访医院里的那个憔悴的女人，阻止她收到那封推荐信和前往城堡，而这可能是最安全稳妥的抉择。男子离开医院时，又回头瞥了一眼建立在石架上的医院；在隐约的风脉中，滚石们正在命运中流动。

于是前往下个地点时，他再也看不见未来里断成两节却苟活的女人。他看见了成为黑帮的自我，正直，刚正不阿却屡屡受伤。他反身拧开了香水，泼在了那柄猎枪里——于是暴躁的言辞再也无法发出，自然也没有后续的事——男子走到路边，坐上了路边的出租车，而同样地，他也碰不上那个交警了。

他安静地命令吓呆了的司机前往城堡，抑或是现在应该被称为营地的存在。从他的这个梦境和这个抉择开始，时间开始重新进行。
 
&nbsp;

**5（远旧营地，告别仪式长章，下，其一） 2019.04/06于2020.06.22**

重整旅途是一件非常困难的事。特别是在一个封闭式的，无法窥探的箱子内，显得更为艰难。在第一次告别结束以后，城堡的崩塌和羽园的溶解造就了营地的诞生和繁荣，但这一切应与旅人们无关。镜潋这么想。他们终要离去。想到这里，他更加难过。

他们仍住在之前的地方，并有时仍然去大厅外的工厂或集市添置生活物品。由于城堡的地陷，他们仍然困守于营地，等候路径的修复。这可能需要一年，一年半，或是更久的时间，旅人们不知道。他们唯一知道的是这段时间虽然对于他们而言难以忍受，在理性上来说，则是微不足道的短短片刻。因此，他变得宽慰了起来，并希望尽情地享受这段时间。

因此，友人们向着不同的方向忙碌地做起自己应做的事。光远搬出了大厅，开始清理过去添置的各种物品。C则是向着他所理解的“正确”的事情而去，包括阅读、学习和简朴主义。——他一向反对那些不应该的事物和情感，并仇恨那段过去。所幸他精英的态度，他的仇恨也仅限于口头。这点就像是在18年他新学习到的一样，他仅仅蔑视，并向着前走去。

镜潋仍然住在旧的审讯室里，每日下楼查看大厅内的天青石雕。那座雕像在他每日的维护下，始终维持着漂亮的青色。镜潋有时也造访营地的管理员，尝试询问通往西方的路什么时候打开，而得到的回答仍然是需要耐心等待。他并不沮丧，而是每天努力地擦着石雕，等候着石雕复活的那一刻。
 
&nbsp;

**6（故事.共变纪） 2020.01.07**

男子常常会去思索那些情感究竟是有没有意义的。当社会和道德从高亢的维度降临而俯视人群，将他们托起成熟成的钢铁，他们的情感就再也没有任何反应了。在生活中的重大事件发生时，他也仅仅只是板着脸，并且认为那些充满暴躁的发泄是没有必要的。

事实上也是，不是吗？一切变迁皆从手指开始。他这么想着。

而当他可能在生活的任何一个意外的角落听到这种许久未闻的情感语言，例如一个嘲讽的笑声，充满情绪化和战栗的发言等，他竟有些不知所措，或令他感到烦躁。就像是他在狂风暴雨的海洋上一样，他本身并无法移动，只是被拖着，向着未知的方向走，便像是共振一般，也能称为高亢的R，我们可以称为共变。

他的情感方向逐渐变得低落了。暴躁的情绪逐渐升起，让他想跨过咖啡厅的数个街区，杀死那个发言者。但他又开始迷惘了。他的伦理特质提醒着他自己：这样的发泄是合理重要的；只是这一切似乎将他拉回到往日的每通电话。在这样的日子里，他只想每天沉睡过去，不愿意面对现实。
 
&nbsp;

**7（远旧营地，告别仪式长章，下，其二） 2020.04/05.23于2020.06.22**

在M的镜像体离开的时候，镜潋就已经很明白她的忠告内隐的含义。在这段旅程中，化身为他的情感起到的作用微乎及微。相互扶持走过旧大陆的过去已经彻底结束；现在的他，只是造就第一和第二次人格战争的凶手，没有其他。

因此他开始郑重考虑自己的未来。每当营地刮起飓风的时候，他往往攀上错落的山峰，站在高处，注视着山下的营地。当光远和C都不明白他在想什么的时候，他就一跃而下，展开滑翔伞乘着风回到小型城堡的拱顶，再下楼，闭门不见。而大厅内的天青石雕什么时候竟然消失不见了，光远感到非常意外，急忙追问镜潋。“我搬到山上了。”后者简短地回答道，也并不说明为了什么原因。三个旅人们在西方通道打开的前夕，向着三个方向背道而驰，这让光远感到有些混乱。“你应该去山上看看。”镜潋这么告诉光远道，也并不告知理由，继续把自己关在房内。

在这样的前夕内，营地外的山脉开始悄然变动。当光远注意到这件事情的时候，地形已经变化地极快了。他所经常拜访的山脉现在已经升到高处，现在要爬上山得非常费劲才能做到——而它连接着向着西方的通路。这意味着他将需要很快搬离营地，并住到山上了。光远这么想着，爬到山上，看着C仍然在山脉的那头忙碌。这时，他才注意到镜潋所说的到山上看看，究竟是什么意思。

和营地无关。荣格城堡的废墟已经被分裂成三块，随着地形的变迁，这三块领土之间的鸿沟越来越明显。如果说通往西方的通路和C正在忙碌的地域的海拔差仍然属于同一条山脉，那么营地和周边的丘陵则渐渐被来自羽园的森林所掩盖。换句话说，他很难再回去了。光远也第一次看到了被搬到丘陵上的天青石雕，在那儿，镜潋正默默地做着，陪伴着石雕。光远有些急躁，急忙下山。

“我不明白你想做什么。”
 
&nbsp;

“我觉得可能我们得暂时分开了。在西方的城堡中，‘我’是不需求的，而只会引发更深的人格战争。而我在营地里，应该能做的更好——大约是这样吧。”镜潋这么安静地回答光远。“我觉得你是抛弃不了那块天青石雕。”光远有些气急败坏。

“那又怎么样呢？我们都是成年人，应为自己的选择买单，负责。”镜潋垂下眼睛，“我说过了，‘我’是不需求的。我对西方的城池毫无兴趣，我在那儿只能沉睡，并有限地吸收旅途。”“但是我并不觉得为了一块永远无法得到的石雕，我们的旅途将牺牲一整个人形，特别是主人形。”光远质问，“你明知道这块石雕只是理想的构念体，你将永远得不到她的内核；明知自己可能重蹈羽园的覆辙，你仍然要这么做？”

“这和羽园无关吧？”镜潋反而笑了，“我们都明白羽园已经溶解了。而情感的本质应该是‘付出’。这和占有欲、内核或者形体毫无关系。我选择在这里是因为我觉得这样更好，我并不打算有任何行动，因为行动本身就是错误的——我并不应该去祸害他人，不是吗？但是我自私自利，因此我愿意保留这座石雕，因为她让我更加舒适。纵使这段爱欲本就是虚假的，但这已经化为了历史，与我毫不相关了。”

离开营地的时候，光远仍然在苦苦思索这段虚假的经历究竟带来了什么，但最终，他都无法明白。镜潋和他的石雕已经留在了东方的营地和小型城堡内，只派出了伴生体镜明（以下简称M1）默默跟随。而光远和C，踏上了山脉地区。在地壳剧变的巨大声响中，从前的旅人们一人在上向着太阳，另一人在下守护石雕，像极了当初在第二意象中，离别的两人。
 
&nbsp;

**8（故事.傀儡纪） 2020.06.02**

男子从深夜里回巡的时候隐约意识到，在漫长的时间里，一切似乎没有任何意义。谁住在哪座城市，谁在哪儿工作，读书，度过悠久安静的生活，这些都没有任何意义，甚至生与死，它们都没有任何差别。在不冷不热的夜晚里，谁与谁的灯火，并不能共享。想到这里，如三年前一样，他打开冰箱，取出一瓶cider，离开自己黑暗的房间。

夜晚逐渐变得淡漠了，在他的眼里，人造的光和暗色的天空逐渐溶为一体，显现出漂亮的，死一般的灰色。这个选择是一回事，那个选择又是另一回事，但说到底，它们本身并没有任何区别。男子可能选择继续聚精会神地工作，或是贯彻精英主义的自我成长，亦或是在某个大桥下，憔悴地度过一生。这些被称为命运的东西交织着成为了多样性的存在，呈现出瑰丽的，没有任何情感的彩虹色。男子选择这方和那方，或者是直接在某个夜晚自杀，都没有任何区别。他这才意识到，体会到快乐，或当初的没有体会到快乐这件事，并没有什么意义。情感在高昂的天空中，根本不值一提。他摇摇欲坠。

这样的状态不同于之前所述的绝望态，亦不是他在过去所体验的任何一个状态。怀抱着淡淡的感情的他，麻木地做着理所当然应该做的事，或许他可能体会到希望，快乐；或是相反效价的感情。一切融为一体。于是，在滞后的潮汐面前，他在镜中面对自己，并变得沉默寡言。与九年前不一样的是，这次，他主动丧失了欲望。
 
&nbsp;

**9（远旧营地，其三） 2020.11.17**

如果说丘陵是源于童年的意象物，镜潋无非把自己所喜爱的，所憎恶的所有情感都投射到了营地里。在光远离开营地之时，他诚实地告诉对方，自己此时将忠于情感的选择——而这只是不同的选择而已，仅仅如此。他如同研习神学一般将自身的情感放置在了很高的位置，并奉献自己。自12年以来，他再一次解放情感。

他很清楚天青石雕的来源。虚假的情感会随着时间推移，转换为自在的、内生的爱，而这部分爱不需要外在动机。他可能随着外部的消息暴怒、贪婪或是嫉妒，犯下无数多令人战栗的罪恶，但这份爱永远停留在他的心里。镜潋很清楚自己的性格，因此他选择了将这部分情感化为坚硬的石雕，他不再接触对方。友人曾经诫告过他这样的情感终究只会伤害到自己，但他不在乎。他一遍遍地借着石雕内生的光辉舔舐自己的伤口，然后再砸碎石雕，再拼起；再借着光辉舔舐砸碎石雕所带来的伤口。他循环做着这样的行为，内心却感受到了快乐。

这是他新的图式。在爱欲溶解的那个夜晚里，他的心永远留在了上海。

&nbsp;

**10（故事.解理纪） 2020.12.10**

在希望的黑暗中，男子终于踏入新的边疆。

告别是一件很痛苦的事。他常常这么想。从现代化的夜晚离开以后，他到达更安静的生活区域，又前往远旧的营地，再告别所有，踏上虚拟的黑暗。在这逐步的旅程中，男子逐一告别过去的人和事，并与自己和解，做了一个决断。这往往是极为痛苦的，也是极为快乐的。在夜莺的歌声充盈着的天空中飘荡的，是缠绕回转的情感。而当他逐步坚定、封闭自我，告别而成更成熟的人时，他能够用更温和的表情，取出一瓶自己喜爱的cider，泼向过去。

在这样冷静的，解理的，充满逻辑的夜晚里，尽管黑暗，他对于未来无比清晰。
 
&nbsp;

**11（黑暗山脉，其一） 2020.11.24**

光远在踏入黑暗山脉的时候想起了M的诫告。“第八个意象将会是你体验过的，有史以来最为危险的黑暗。”离开亦非城时，她无疑是这么确认并忠告过两人的。这个预言最后实现成人格战争、羽园破坏、深渊和天青石雕事件等多个绝望的过去，其破坏程度不亚于曾经的仙岳医狱与佳境岛。虽然现在他亲手将营地抛在脑后，光远却隐隐约约感觉到，故事尚未结束。

进入山脉的不久，天色便落下了帷幕。在无风无星的夜晚里，光远视线所及看不见任何事物。天穹所带来的唯一的反光被远远的旧营地所吸收，全部集中于天青石雕之上。光远又望了望营地，随着在山脉的逐渐跋涉，他已经逐渐看不清营地了。他所能看见镜潋的最后一瞥，就是后者如同疯子一般用自己的手臂和头砸碎了天青石雕，任凭血液顺着自己脑袋往下流。他的暴怒、嫉妒或是贪欲，更极限所犯下七宗罪的，深陷于迷惑于‘爱’的高亢的感情也竟然令光远受到了一丝影响，他感到不安。

然而旅途还是要前进，前往西方的道路，并没有那么好走。光远想了想，望向了第三人格所在的方向。

他旋即看见一束光。随后，冷静的呼喊声从远方传来。远处，第三人形伴着发光的，安静的P人形逐步走来。“最好先集合，再好好探索这个山脉——这里非常危险。可能不亚于曾经的第五区。”IC握了握心理学人形的手，冷静地说道。“但我们应该怎么办？”光远此时竟突然有些茫然，他同样也握了握处在他旁边的，不会说话的镜潋分身M1。他已经十四年没有与主人格离别了。即便是在佳境岛后者死亡的瞬间、或是在人格战争中互相厮杀的那三年，两位友人也一直在一起。“我们先去找塔。”IC看着他的眼睛，回复道。

“塔？”

“能够指导我们的，前进的道路。”IC十分耐心地解释。对待友人，他反而耐心，安稳，而不是对外的往往冷淡、充满期待。“它将不是意象，但绝对是你们能够在失去方向时的最好指示物，回想一下你遗失的记忆，你在哪儿见过塔的类似物品？”
 
&nbsp;

“原初的暮落晨光塔。镜潋提及的镜湖的塔楼。……仙岳医狱的监视塔……亦非城第五区的回归高塔……”光远苦苦思索。十六年的回忆被逐步地打开了，他想起了更久远的一些故事。“……亦非城的洁白高塔。”这不就是我们要去寻找的事物吗？在暗夜里唯一安稳宁静的远居地，远离所有危险的事物的洁白高塔？

“我们要去寻找山脉中的塔。那可能是与未来的塔相连的。”IC看向黑暗的山脉，无风无星的深夜依然笼罩了整片山脉，形成不规则的，令人畏惧的黑暗。“我的前期调查已经发现了一些线索，虽然你不知道，在这座山脉里，不是荒无人烟的。”

“我只能透露这么多了。”IC叹了口气，又握了握心理学人形的手。他抬起头，眼睛炯炯有神。“我们要去寻找一座发信塔。一座无线电波塔。从这座塔，我们可以寻找到其他发信人。”
 
&nbsp;

**12（故事.长扬纪） 2020.12.07**

在高亢的白昼中，男子终于看见了疾风的形状。于模糊的梦中，他记起他曾经跋涉在无尽的苔原地貌中，深一脚浅一脚地前往冰壳深处的火山。他甚至还能听到瀑布的流动声逐渐缓慢，天空逐渐被冻结了。明亮或更亮的斑纹撕开了整个白昼，并产生如同幻觉一般的雷鸣。男子摇了摇头，看向远处促狭的地貌。

在造物者宏大的场景里，一切都变得没有意义了。极远处可能是海洋——但至少，眼前的景色里，只存在着稀疏的植被带。他抖了抖身上的冲锋衣，又开始一瘸一拐地在这高原里跋涉，前往远处的港口。他逐渐出现了特别的幻觉——极为末日一般的影像在他的眼前逐步出现，他有些恍惚。当自己的视觉也出现了偏移的时候，他应该去相信谁？男子此刻唯一想到的是自己受邀的那幅场景，他又抬起头来仰望更加刺眼的天穹。

斑纹一般刺眼的高光照亮了整片永久冻土。在他的面前，大地被缓慢地裂变成数块；天空中的光点并着更为细致的，安静的水滴一起落到地壳的深处，在那儿，岩浆和热土发出低沉的、细微的咆哮声。男子在下定决心前往远方的最后一刻，又忍不住回头看了看曾经拜访过的栈道。他最后一瞥唯一能够看到的是，在那儿，火与雨正在同时降临整片世界。

&nbsp;

**13（远旧营地，其四）2022.06.29, 07.16**

镜潋抬起手，最后一次地，轻轻地抚摸他面前的那块天青石雕。被他暴怒着打碎的石雕在数个月内被他一遍遍细心修复后旋即打碎，早已丧失了原本的形状。现在的石雕似乎变成了一个扭曲的，充满他期待的异形怪物。

或许期待本身就是怪物。他凝视着天青石雕，那曾经是他期盼的未来的自己，却随着对现实的重构和理解，化为灰烬，飘洒在亦非城新区的上空。随后，疾风将它们带向了充满未知的山脉，变成了零星的火点，如萤火虫般闪烁了一下，便消失不见。

&nbsp;

命运是多样的，发散的。

&nbsp;

他回头凝视着山脉的入口，那是友人们离别的方向。在他的身后，远旧营地里的人群依然喧嚷，忙碌。但那已和他无关。在燃烧得只剩一些余烬的火堆旁，只剩他和负面情绪的集合。他最后叹了一口气，敲了敲天青石雕。后者应声化为了尘沙，落在名为告别的盒子中。盒子应声落地，发出清脆的咔哒声。虽然在众生离绝的那个夜晚，他没有选择逃亡，但在往返的晨光下，他逐渐回想起了一些东西。

或许他潜入这黑暗太久了。在无光深海的十数年内，他已经逐渐忘记了塔楼新生的晨光，镜湖摇摆的波浪，与森林内短促的鸟鸣声。黑暗已经逐渐侵蚀了他的内心，他已经很难再想起拥抱着幻想的玩偶是什么感觉，雾色的森林里香甜的植物气味。笔和墨水已经随着旅途逐渐被遗忘，掉落、散开、蔓延。原始的他，应是单纯明快的旅行者，覆盖情感的温言善语和苦痛忧愁。他突然回想起了圣诞大厅里顽皮安静的精灵，虽然那是虚假的，但是与温柔、坚韧、成熟和陪伴的第一条通路不同，她直接对应了原始故事里的第二条通路。

远旧营地里的事物似乎没有那么刺眼了。镜潋逐渐适应了这新生的居住地。这也许是暂时的，但舒适的暗夜远居地。镜潋想着。他弯下腰捡起名为告别的盒子，转过身，面向远旧营地。在他的面前，人群彼此之间孤单、独立、却又喧喧嚷嚷地走过。他开始慢慢地走向营地的外周，在他的身后，影子开始缓慢地，从他的深处向地上脱离。

&nbsp;

命运是未知的，不可预测的，也是美丽的。

&nbsp;

镜潋漫步走过营地外周的小道，他开始懂得注意和慢慢欣赏这个曾经神秘的营地。尽管小道的周边野草仍然旺盛，在不远处的营地边缘，旅人们早已清理出了一片混杂但平缓的沙地。他们生起不同颜色的篝火，用于休息、整顿和庆祝。更远处是已经难以看清的，他的来源——从荣格城堡崩毁而来的三层交易大厅、大厅周边的斜坡（用于快速登上顶楼）和斜坡下的小型工厂。更远处是模糊的王政大厅，已不可见，但镜潋清楚他就在那。

镜潋无意靠近营地的核心部分。那是他的来源，但他对政治的交涉和圣诞的篝火皆没有兴趣。随着漫步于类似营地保护墙的零星小道，他看见了更多美丽的、平和的事物。这些事物能让他回想起他曾经漫步于雾色森林中采撷的蘑菇与花瓣。影子慢慢地随着步伐被撕扯开，消亡于小道两旁的灌木丛里。随后，他逐渐发光了。

&nbsp;

镜潋愣了一下。他逐渐发光了。他低下头看了看自己，在核心深处的鬼魂里，他的确散发着虽然微弱，但是安静、凝重的光芒。他突然听到一阵窸窣的声音，抬头看向周边，却看到随着他内心的光辉，小径旁的植物四散逃去。在他的左侧，营地内的人群依然在喧喧嚷嚷地做着自己忙碌的事情，没有人注意到他。营地内的喧闹声和他无关，此刻，小径变得安静起来了。

镜潋摇了摇头。“这是为什么？”他不明白。他尝试着走了两步到小径旁的杂草处，除了微弱的光辉外，他的身体一切正常。于是他只能在杂草里坐下，开始研究自己的身体。光辉是正常的，如同人造的太阳一般，不自然却温和。随着光芒的撕扯，在人格战争最后溶解于他身躯里的D开始继续消融，内化为他内心的一部分。人格的尺度逐渐平衡了。砝码被逐渐抛出，天平倾斜向另一方，发出沉闷的钟声。

镜潋挠了挠头，他还是不明白发生了什么事。当他把手放下时，触碰到了一个不自然的东西。他向他的右手看去，在他的手掌中心，是一棵沾染上影子的蔷薇科植物，虽然摇摇欲坠，却在他身边安静绽放。

&nbsp;

**14（故事.复兴纪） 2022.07.16 in 2022.08.24**

男子举起枪，举起弓，或是举起剑来。幻想的武器在他身旁变换着，他在寻找趁手的物品。随后，他目视前方，对着冷峻空旷的街道，——开出一声空枪。“砰！”他为自己配上音，对着街道回应。没有回声，所有的语音数据被卷入虚空中，化成碎片。在冷静空旷的街道里，他放下武器。整个街道只剩下他和永生的黑暗，沉默对抗着。在这样散发着停滞的夜晚里，他慢慢地开始体验起曾经的感觉。他螺旋上升。

远处火与雨的梦境正在逐渐消散，在深沉的夜晚里，他望向窗外，逐渐想起了复兴的感觉。在窗外的大街上，灯光如海连成平滑的曲线，一直绵延到模糊的视野之外，他看向身边的杯子，又举起来，喝了一口。变冷的咖啡有些苦涩。

&nbsp;

这种舒适的、安稳的场景已经很久没有体验过了。在数年以前，男子曾经体验过虚假的，建立在可知论旗下的精英主义。在醉生梦死的超市里，他推着车走过自己理想的国度。那样的生活也是安静的、平缓的、也是令人沉醉的。在舒适的环境中，他想象过、也憧憬过未来的场景，随后随着命运的滚石，坠入深渊。如今的他，从浅小的深渊尽头爬了上来，再不会被梦境所困扰。他的眼里闪烁着通透的光。

这样的复兴难能可贵，他珍惜当下的每一天。在发着光的时间里，他开始体验和享受生活。

&nbsp;

**15（黑暗山脉，其二） 2022.07.16**

“第三座。”  
光远推动推杆，电波设备开始传来滋滋的响声，IC和他默不作声地听着。电波塔顶层突然刮起了一阵冷峻的风，光远忍不住缩了缩身体，却踩空了脚底镂空的铁网，不由得滑了一下。“小心。”IC拉住了他。  
“谢了。”光远狼狈地站起身，看向电波塔的下方。最早攀登发信塔时他还有些恐惧于下方的高度，深不见底的山脉仿佛下一秒就能将人吞噬。在这样的黑暗中，旅人们什么也看不见，只有电波塔拉起的线割开了黑暗的苍穹，一直贯穿到山脉的深处。  

电波信号滋滋地持续了一段时间，慢慢地模糊下来，最后沉寂。“没有回应。”IC锁紧了眉头，“……嘛，早该料到。”  
“嗯。”光远垂下眼睛，叹了口气。IC默不作声地对他点了点头，从信号塔的墙上取下差点被疾风刮灭的火把，递给了他。后者接过火把，转向信号塔的另一侧，在那，一个原始的燃烧炉和相应的灯光转换器陈列在那。IC开始爬下塔楼，光远则注视了一会燃烧炉，随即和镜潋在羽园时做的一样，将火把扔入燃烧炉。火焰开始缓慢、微弱却顽强地升起，光远摇了摇头，将燃烧炉关上，仅留一个通气的孔道。随着炉子内部的燃料被火把引燃，灯光转换器开始运行，塔楼的顶层开始发出微弱的光。此刻，塔楼不再是单纯的无线电波塔，而变成了一盏指引旅人方向的灯塔。“孩子，完成生命的最后一盏灯。”看着微弱的灯光，光远恍惚间想起了在亦非城尽头老人对他说过的话。  

&nbsp;

那已经是很久以前了。  
“快走吧。”耳边传来IC的声音，他才清醒过来，看向下方。IC扮演着的C、漂浮着的洁白人形和伴生体M1均在塔的下方仰起头，等候着他。“来了。”光远有些抱歉地说。他迅速地拎起背包，熟练地爬上铁质的直立爬梯，向下滑去。  
“每到一个塔这都是你最后要做的事，是为了镜潋吗？”IC盯着友人熟练地从高处滑落到地面，突然发声询问。“不完全是。”光远拍了拍身上，抖落因为降落带来的尘土，“也为了山脉中的人群。”  

&nbsp;

“灯是极为重要的。连贯起的灯流可能对大部分旅人不重要，却是一些人心中的丝线。”光远想了想，回答道。他们深入这山脉已有数年，已经完全看不见来时的路，也无法再站在高地俯视远旧营地所在的方向。此时的他们，除了手中自己绘制的地图，便只能看见一片漆黑。随着数年内的旅行，他们遇到了无数同样在山脉中旅行的人群。有恶意的，也有善意的。每个人形形色色，极为不同，他们也结识了一些旅行团，以及造访过一些点亮的或是未点亮的发信塔，当然，均未得到回应。充满黑暗的山脉是极为危险的，旅人们被自己的影子和来自大山的影子所包围，侵蚀，在此处的每一步都需要极为谨慎，在狂热的，殊死的剧场内，每个人都在和自己内心的野兽搏斗。“我只是觉得灯是有用的，无论持续多久。”他回答道，“走吧。”

&nbsp;

“她在远方等你。”  
迈动脚步的一刻，光远突然回想起了老人的下半句话。他不由得向远旧营地的方向和山脉的尽头看去，却什么也看不到，他们已经深入山脉很远了。

&nbsp;

**16（故事.旋涡纪） 2022.08.24**

男子将头抵上镜子，看向镜子中的失焦的、膨胀的自己。镜中的自己散发着神圣的光芒，眼里带着平和、温柔、但十分危险的情感。他的眼中漆黑一片的瞳孔逐渐扩散、扭曲，形成了危险的旋涡。

这样的人在任何情况下都是危险的。他这么判断自己，又咧开嘴，普通地笑了。他能感受到他正散发着不可认知的神秘气息，这样的气息让他对自己感到恐惧。虽然如此，从他的平日里观察去，他也仅仅只是在说着极为保守谨慎的温言善语，用稳定态面向广阔的色谱。这样的人能够根植于常态化的社会里，却也极为危险。

极为危险。

&nbsp;

在发着光的时间里，男子幻想过自己被猎杀的场景。他作为病患的日子又回来了——在每个群际场景低着头嘿嘿地笑着，做一个简单的、危险的、却又对人无害的离群值，像极了十多年以前在深夜街道时，踢着石头跟随的那个孩子。他的眼里逐渐充斥着疯狂却又圣洁的气息，旋转着汇聚成深不见底的旋涡。与纯粹的黑暗与暴躁无关，这样停滞的光带给人的，才是最为深沉的颤栗。虽然他对于未来毫无概念，梦境唯一给他的解释只有举着枪的猎杀场景。神圣的，充满光明的人类，眼里包容着残忍和混沌，应声而倒。这将是下一个启示。

&nbsp;

但它代表着什么呢？我又是谁？在知识的边疆里，男子寻找不到任何对这个现象解释的根源，不可知论主导着的唯一情感和神秘学朝向的将是童年里纯净的河流。理性的人形告知男子，所能预见的自己应是危险的，但男子不信任理性。出于疯狂的概念，他更愿意观察在这样的场景下，光辉会带来怎样的热量，引发怎样的爆炸，吞噬掉怎样的飞蛾。在可能的场景中（例如雪），戏剧性的变化将如何产生。阅读自身的故事，这将是他渴求的。男子这么想，不惮以最坏的恶意猜测自己。冥冥之中，附着于他身躯的神圣概念悉悉地告诉自己：

&nbsp;

*这些世界不需要一些人。很遗憾，你可能正是其中之一。*

&nbsp;

**18（故事.偏转纪） 2022.08.24**

故事的后日谈即将坠入终点 在最后一秒的呼救里 我不可能听到关于自己的更多信息 异端的故事最后会回归常态 艺术化的作品也将走到重点 化为知识的偏转打击 赋予人类不同的诚惶诚恐 俯首称王 珍惜每一次写作的灵感时机吧 所有的衰老将回归自身 透支你生命的每一刻隐喻 每一个音符 甚至每一个人生的谜题 我不可能再更多地找到关于自己的秘密了 比起故事的归纳我更愿意关注故事的生成 将自己化身为决策的疯狂点真是一件好事 虽然这会葬送自己  
到底是什么阻碍了我找到更多的信息？不可能是十数年前的故事其已经消解于重建坠落的终途 也不可能是自身的障碍 大家可能不明白劝阻是无用功的 每个人都有属于自己的河流 但是我清楚 那么终究只能归咎于风脉中的滚石 冲向色谱中唯一的点？这可能是正确的 但也更令我失望  
看 半岛的旅途也走到了尽头 偏转的世界光线也将回到我的额边 什么能够成为我的期待 我仍然苦苦地在思索着

&nbsp;

**21（黑暗山脉，其五/落日河流，上） 2022.08.24 P1**

*故事的后日谈即将终结于落日河流。你将驻扎于落日的河边，寻找粮食和篝火。你将伴随着血红色，前往溪流旁取来一些木头，将它们折断。这些绯红的植物将流出鲜艳的、暗红色的血来。不用顾虑太多，请用血浇灌你的火焰，这也是你的一部分。除了你的幕布以外，请你洗净每个你生来的肮脏物品，随后，将他们折回原样（unfold）。不用顾虑太多，他们会自行修复折痕，回到原始的状态。*

*这不是童话的一部分，这本身即是童话。不协和音已化成对照的镜子，助你袅袅上升。*

&nbsp;

*愿你在森林的背面，看见悬崖。*
