---
title: 『 倦鸟归去. 』
author: C. from Genesis
date: '2015-09-04'
slug: XYMHC
categories:
  - Story
  - XY Mental Health Centre
tags:
  - XY Mental Health Centre
---

我最近做了一个很漫长的梦。

这似乎是万能的起手式。在每一个你写不出任何东西的夜晚，它都是一种告慰。当我拉开窗帘的时候，英国碧蓝的星空在对我闪烁着，一切都好。

<!--more-->

我最近做了一个很漫长的梦。
 
&nbsp;

这似乎是万能的起手式。在每一个你写不出任何东西的夜晚，它都是一种告慰。当我拉开窗帘的时候，英国碧蓝的星空在对我闪烁着，一切都好。

来坎特伯雷已经抵三个余月了。快速适应过这里的生活，与身旁的中国学生一比较，发现自己似乎也不是那么一无是处，甚至可能更强。这令我暗自窃喜，而同时心理学带来的自我慎戒也在提醒我去学习更多，这令我在平稳中逐渐发展，努力不让别人赶上。

总之，一切都好。
 
&nbsp;

这里的生活很平淡。除了生活费用高了一些之外，我顺手点了料理的技能。出其意料的是，我还是那样内向而不善言辞。当外国舍友问我去酒吧和夜总会的时候，我总是拒绝。我不知道为什么，大学的这四年是改变了我很多，从高中时代神经症患者的畏缩到大学时代更加自信的存在，我似乎正在沿着一条逆着原始的我的方向走着——这是正确的，亦或是非正确的？任何人都无法给出答案，包括我自己。我还是那个我，不想和别人主动交流，我只想活在我自己的世界里，做着安稳麻醉的梦。

以上，晨夕所言。
 
&nbsp;

而七之后的旅行也终于进行到了中期。步入荣格城堡之后，正如那次心理治疗课自我催眠后我所说出的故事一样，人格之间的战争仍在继续。意外的是，光远倒在了东方的城堡，而跟随晨夕进入荣格城堡西区的是被捆绑了三年的镜潋。这样的结局谁都没有想到，谁也不会想到。将来在这座城堡中的故事会是怎样，仍然还是一个谜。

总之，羽园还是毁掉了，我也不可能回去了。
 
&nbsp;

我每天都会做漫长的梦。不是日日悲梦，也不是欢悦的幻觉，是更奇异的一种存在：像是倦怠的鸟儿一般，归去之时，站在树枝上做的一个疲倦的，漫长的梦。梦中全都是他的过去，从孩童时代那些无法更清晰的隐约的梦，到三年前那些无意义的吵架，一切都在变迁。

而当我醒来时，我感到异常的疲倦。无关物理，只是心灵。托这些疲倦所赐，我看见了幻影。

语言课程的宿舍在Park Wood，深林中的小屋。从Laundry洗完衣服，提着dry machine烘干的温暖干燥的衣服回去时，我会顺着Park Wood那林中小道往回走。一路慢慢走着，每次都会看见幻影。

这些幻影无关物理，而是心灵。

先是慢慢显露出来的小学时代的骄傲的我，很短暂，一纵即逝。随即是创网的那些人，一个接一个出现在道路的左边：他们像是在讨论些什么。我无法侧过耳去听，因为我的速度太过于快，他们很快就被我抛在了后面。随后是高中时代瑟缩的我，蹲在Marley 11th房屋外的角落瑟瑟发抖，用着恶毒和绝望的眼神盯着世界。接下来是两个发着光的人在吵着架，他们之间的光芒相互抵御着，我已无法辨认出他们的身形。他们都很善良，他们都发着光，只不过他们的光芒无法容纳彼此而已。

走到路的最后，被我最后抛在路边的幻影是褪去光芒的我，安静地看着我自己。而我站在Marley 3A的窗户旁，英国的蓝天正在蜕变成夜晚，夏令时即将过去，寒冷的冬天要来临了。

然后我打开门，回到宿舍，没有回头再去看那些幻影，不敢还是不想，我也不明白。

话就说到这里吧。似乎也没什么可以报告的，总之，一切都好。语言课程已经顺利通过，从今日开始，我将在这里攻读研究生，继续我的心理学之路。最近常听的一首歌是杨乃文的我离开我自己，我已经忘记这首歌是从谁那里听到的了，只不过，竟觉得它无比契合我现今的想法和我的曾经。
 
&nbsp;

>因为明天还剩一寸记忆  
>泪水染红眼睛  
>所有的过往还灿烂无比  
>却不可及  
>对世间的离别深信不疑  
>因此才会相依  
>没等看见年华流失散尽  
>就变灰烬  
>你问我发生了什么  
>无光的夜不动声色  
>心似淬火不能触摸  
>温柔无因果  
>用天真换一根烟的光阴  
>我离开我自己  
>像倦鸟归去留下的空寂  
>安安静静  
>对世间的离别深信不疑  
>因此才会相依  
>没等看见年华流失散尽  
>就变灰烬  
>一霎风雨我爱过你  
>几度雨停我爱自己  
>如何结束一身冷清  
>梦来了又去  
>用天真换一根烟的光阴  
>我离开我自己  
>像倦鸟归去留下的空寂  
>安安静静  
