---
title: 『 夜巡. 』
author: C. from Genesis
date: '2018-05-04'
slug: XYMHC
categories:
  - Story
  - XY Mental Health Centre
tags:
  - XY Mental Health Centre
---

写这篇日记时，我想起前几天我坐上的那班回家的飞机。

<!--more-->

>“这里是我的故乡，只有水和土地。人们也在逐渐衰老，失去活力。——我并不觉得这是最美的地方，也不觉得这里充满着可能性。但是……我想向折木同学介绍这里。”  
>——冰菓，第四卷

写这篇日记时，我想起前几天我坐上的那班回家的飞机。飞机起飞时，我正好把手机关上，看向舱外的风景。当时的我所能看见的，是在一片死寂，毫无星点的夜空中闪烁着的巡航灯。因为不允许打开手机，我只好在脑海里开始播放牛尾宪辅《Night Cruising》。随着起飞时沉闷的气流声和持续闪动的巡航灯，我随着自己的幻想，沉沉睡去。

《Night Cruising》倘若翻译成中文，最直白的翻译是“夜间巡航”，也是我个人认为很酷的翻译。然而契合到它所存在的作品《乒乓》中，附和到当下的情境，较为合适的翻译应为“巡逻”而非“巡航”，作品是一篇有关于人生成长和选择的故事——这大概并不是当下的重点。回到厦门的时候，深夜依旧。亦非城D区依然向我呈现着它无风无星的漆黑深夜，正如一往我在飞机上所遇见的夜晚一样。我又想起在过去策划的小说中，随着夜晚奔驰的高中生，那可能是我的化身。

夜晚到底对我意味着什么？应该说是过去数年内我所有的支撑物。夜晚可以意味着逃离现代生活，也可以理解为自我求助于孤独时，所爆离出的创作欲望。过去的数年内，我无疑是喜爱着这长久的夜晚的。对于我来说，离开白昼的世界而将去往所有人沉睡的世界——那儿充满着贪恋般的好奇、罪恶的行为与思想，以及一些只有自己能够解读的东西。

所以一如既往地，我常昼伏夜出。一直到随着晨夕转变成表里一体的控制性人格，有条不紊地进行着光远的音乐计划和自我的心理学工作后，才有了因为“疲倦”所导致的异常。这种所谓的异常，从幻想的角度，就犹如是你将潜入这梦境和深夜时，猛然被人拉扯回来。对于你来说，这极为危险；对于这世界来说，则极为安全。我这么想着，思绪又被拉回到现在：我坐在平稳行驶的的士里，电台在放着令人沉迷的音乐，身旁的路灯和夜色疾驰而过，深夜又一次带给了我安全感。

这种感觉就好像是你在竭尽所有心理能量时，不得不还原以母胎的姿势，蜷缩着，被迫着陷入安全的睡眠。你不会有梦境亦或是其他的负担，只是沉沉睡去。我又努力去倒数自己切换成晨夕时，亦或是荣格城堡西方时，亦或是更久远的人格战争时经历的每个夜晚。可能是深夜中沉默着骑着车飞驰而过西藏北路的自己；亦或是半夜的坎特伯雷狼院洗衣房里，抱着温软舒适刚烘干的衣物的自己；可能还是夏夜里因为现实而焦虑，睁着眼睛睡不着的自己，身边的手机却循环着有关于夜晚的歌曲。

所以你看，抒发情感什么的，完全没有必要。即便我明白那些过去都属于我自己，或者是我会守卫夜晚一样，夜晚也会回馈予我情感。这些情感终究会犹如红柳木一般，构建成生硬而有温度的支架，将我束缚在最为安全的框架内，让我如同母胎，安全地陷入深夜，沉沉睡去。最后在这深夜内可能剩下的，也就只有如同呼吸般闪动的巡航灯。
